global:
  systemDefaultRegistry: ""

systemUpgradeController:
  image:
    repository: rancher/system-upgrade-controller
    tag: v0.7.5

kubectl:
  image:
    repository: rancher/kubectl
    tag: v1.25.7
